id: A4AB94173
title: Prayer for the Long Life of the Third Dodrupchen, Jigme Tenpai Nyima
type: translation
pechas:
- I822AAA81
- I0F06B26F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:34:14.591826
  last_modified_at: 2023-01-04 12:34:14.591835
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I822AAA81/7EC9: D895
  I0F06B26F/0464: D895
